In [1]:


# functions used throughout analysis

from __future__ import division
from IPython.core.display import HTML
import numpy as np
import pandas as pd
from collections import Counter
from scipy.stats import mode

pd.set_option('display.max_colwidth', 1)



def loadFiles(src_dir, fnName):
    fn = src_dir + fnName
    df = pd.read_csv(fn, delimiter=',')
    return df

def getDfColumns(df):
    return list(df.columns.values)

def columnString(dfList):
    return ','.join(dfList)

def findSingleCells (df):
    crossMatrix = df.as_matrix()
    single = len([ row[i] for row in crossMatrix for i in range(len(row)) if row[i] == 1 ])
    totalcells  = len([ 1 for row in crossMatrix for i in range(len(row)) ])
    kplus = totalcells - single
    percentsingle = (single/totalcells )* 100
    maxCell  = np.amax(crossMatrix) 
    minCell = np.amin(crossMatrix)
    meanCell = np.mean(crossMatrix)
    medianCell =   np.median(crossMatrix)
    return single, kplus, totalcells, percentsingle, minCell, maxCell, meanCell, medianCell

def getCrossTab(grpField, fieldList, margin=False):
    crossTab= pd.crosstab(grpField, fieldList,  margins=margin)
    return crossTab

def getSingleCellInfo( datasetName, crossTab, grpFieldList,  fieldListString):
    single, kplus, totalcells, percentsingle, minCell, maxCell, meanCell, medianCell = findSingleCells(crossTab)
    reportInfo =  "<div> *********************** </br>"
    reportInfo = reportInfo +  "<h3>" + datasetName +  ":</br>" + grpFieldList  + " By " + fieldListString + "</h3>"
    
    reportInfo = reportInfo + "<p><b> Total of number of cells in " + datasetName + "- " + fieldListString + " By " + grpFieldList +": " + str(totalcells) + "</br>" 
    reportInfo = reportInfo + "Number of Single Cells in " + datasetName + "- " + fieldListString  + " By " + grpFieldList +": " + str(single)+ "</br>"
    reportInfo = reportInfo + "Percentage of Single cells in "  + datasetName+  "- " + fieldListString +" By " + grpFieldList +": " + str( percentsingle) + "%" +"</b></br></p>"

    reportInfo = reportInfo +  "<br> Min cell value in crossTabs: " + str(minCell) + "</br>" 
    reportInfo = reportInfo + "Max cell value in crossTabs: " + str(maxCell)+ "</br>" 
    reportInfo = reportInfo + "Mean cell value in crossTabs " + str(meanCell)+ "</br>" 
    reportInfo = reportInfo + "Median cell value in crossTabs: " + str(medianCell)+ "</br>" 
    reportInfo =  HTML( reportInfo )
    return reportInfo 
    
    
def makeOutput(datasetName, src_dir, fnName):
    df = loadFiles(src_dir, fnName) 
    df_column_names =  getDfColumns(df)
    titleStuff = "<H1>**************************************</br>" + "Dataset: " + datasetName  + "</br>"
    titleStuff  = titleStuff + "<p> Columns: "+":</p>"
    titleStuff = titleStuff + "<p>" + ", ".join(df_column_names) + "</p></H1>"
    titleStuff = HTML(titleStuff)
    return df, titleStuff

def makeCrossTabInfo( grpField, grpFieldList, fieldList, fieldListString,  datasetName):
    crossTab = getCrossTab( grpField, fieldList)
    single_cell_info = getSingleCellInfo( datasetName, crossTab, grpFieldList, fieldListString)
    return crossTab, single_cell_info

In [2]:

datasetName = "Juvenile Probation Juvenile Hall Admissions"
src_dir = '/home/ubuntu/workspace/source_data/'
fnName = 'Juvenile_Probation_Juvenile_Hall_Admissions.csv'
        
grpFieldList = 'Detention Year'
df, titleStuff = makeOutput(datasetName, src_dir , fnName )
titleStuff

In [3]:
grpField = [ df['Detention Year']]
fieldListString = 'Ethnicity,Gender'
fieldList = [ df['Ethnicity'],df['Gender']]
crossBy, single_cell_info = makeCrossTabInfo( grpField, grpFieldList, fieldList, fieldListString,  datasetName)
single_cell_info

In [4]:
crossBy

Ethnicity      african american       asian      hispanic       other       \
Gender                   female male female male   female male female male
Detention Year
2011            144              502  15     98   52       209  1      8
2012            122              389  17     64   32       186  0      17
2013            108              351  18     77   40       147  5      6
2014            102              317  5      59   32       154  0      4
2015            94               319  7      51   39       126  0      8
2016            54               184  5      19   20       49   0      8

Ethnicity       white
Gender         female male
Detention Year
2011            13     31
2012            7      36
2013            10     37
2014            6      19
2015            11     28
2016            5      6

In [5]:
grpField = [ df['Detention Year']]
fieldListString = 'Ethnicity,Gender,Age At Detention'
fieldList = [ df['Ethnicity'],df['Gender'],df['Age At Detention']]
crossBy, single_cell_info = makeCrossTabInfo( grpField, grpFieldList, fieldList, fieldListString,  datasetName)
single_cell_info

In [6]:
crossBy

Ethnicity        african american                          asian           \
Gender                     female           male          female
Age At Detention            13-17 18+ <=12 13-17 18+ <=12  13-17 18+ <=12
Detention Year
2011              134              7   3    479   14  9    14     0   1
2012              107              10  5    356   22  11   17     0   0
2013              95               11  2    303   23  25   18     0   0
2014              88               12  2    283   21  13   4      1   0
2015              86               8   0    277   28  14   6      1   0
2016              53               0   1    162   17  5    5      0   0

Ethnicity              ... hispanic       other            white           \
Gender            male ...     male      female  male     female
Age At Detention 13-17 ...      18+ <=12  13-17 13-17 18+  13-17 18+ <=12
Detention Year         ...
2011              93   ...  26       3    1      8     0   12     1   0
2012              61   ...  29       2    0      16    1   6      0   1
2013              68   ...  12       1    5      6     0   9      1   0
2014              56   ...  24       0    0      4     0   6      0   0
2015              48   ...  19       2    0      6     2   10     1   0
2016              19   ...  11       1    0      5     3   4      1   0

Ethnicity
Gender            male
Age At Detention 13-17 18+
Detention Year
2011              30    1
2012              31    5
2013              37    0
2014              16    3
2015              27    1
2016              5     1

[6 rows x 26 columns]

In [7]:

datasetName = "Juvenile_Probation_Juvenile_Hall_Daily_Population"
src_dir = '/home/ubuntu/workspace/source_data/'
fnName = 'Juvenile_Probation_Juvenile_Hall_Daily_Population.csv'
        
grpFieldList = 'Ethnicity'
df, titleStuff = makeOutput(datasetName, src_dir , fnName )
titleStuff

In [8]:
grpField = [ df['Ethnicity']]
fieldListString = 'Detention Year, Release Year'
fieldList = [ df['Detention Year'],df['Release Year']]
crossBy, single_cell_info = makeCrossTabInfo( grpField, grpFieldList, fieldList, fieldListString,  datasetName)
single_cell_info

In [9]:
crossBy

Detention Year   2009 2010 2011           2012           2013      2014       \
Release Year     2011 2011 2011 2012 2013 2012 2013 2014 2013 2014 2014 2015
Ethnicity
african american  0    42   598  47   1    472  38   1    431  28   381  38
asian             0    1    58   2    0    27   2    0    46   2    29   2
hispanic          1    31   245  14   2    199  18   1    181  6    171  15
other             0    6    57   5    0    59   10   0    53   5    36   1
white             0    2    40   4    0    40   3    0    42   5    24   1

Detention Year   2015      2016
Release Year     2015 2016 2016
Ethnicity
african american  392  21   238
asian             22   2    2
hispanic          151  14   69
other             37   5    30
white             36   3    11

In [10]:

datasetName = "Juvenile_Probation_Juvenile_Hall_Releases"
src_dir = '/home/ubuntu/workspace/source_data/'
fnName = 'Juvenile_Probation_Juvenile_Hall_Releases.csv'
        
grpFieldList = 'Detention Year'
df, titleStuff = makeOutput(datasetName, src_dir , fnName )
titleStuff

In [11]:
grpField = [ df['Detention Year']]
fieldListString = 'Age At Release, Length of Stay In Juvenile Hall Custody'
fieldList = [ df['Age At Release'],df['Length of Stay In Juvenile Hall Custody']]
crossBy, single_cell_info = makeCrossTabInfo( grpField, grpFieldList, fieldList, fieldListString,  datasetName)
single_cell_info

In [12]:
crossBy

Age At Release                          13-17                                  \
Length of Stay In Juvenile Hall Custody     1   2   3   4   5   6   7   8   9
Detention Year
2009                                     0     0   0   0   0   0   0   0   0
2010                                     0     0   0   0   0   0   1   0   1
2011                                     31    55  89  35  43  37  25  45  39
2012                                     22    28  65  30  30  37  31  29  31
2013                                     24    43  52  38  35  24  18  14  19
2014                                     14    37  52  25  23  24  10  13  8
2015                                     21    31  65  32  27  14  16  20  19
2016                                     4     24  49  10  19  12  6   2   7

Age At Release                              ... <=12                          \
Length of Stay In Juvenile Hall Custody  10 ...   27 28 29 31 40 41 47 52 56
Detention Year                              ...
2009                                     0  ...  0    0  0  0  0  0  0  0  0
2010                                     3  ...  0    0  0  0  0  0  0  0  0
2011                                     22 ...  0    0  0  0  0  0  0  0  1
2012                                     15 ...  0    1  0  1  0  0  0  0  0
2013                                     18 ...  1    0  1  0  0  0  1  1  0
2014                                     6  ...  0    0  0  0  1  0  0  1  0
2015                                     14 ...  0    0  0  0  0  1  0  0  0
2016                                     10 ...  0    0  0  0  0  0  0  0  0

Age At Release
Length of Stay In Juvenile Hall Custody 71
Detention Year
2009                                     0
2010                                     0
2011                                     0
2012                                     0
2013                                     1
2014                                     0
2015                                     0
2016                                     0

[8 rows x 382 columns]

In [13]:

datasetName = "Juvenile_Probation_Log_Cabin_Ranch_Admissions"
src_dir = '/home/ubuntu/workspace/source_data/'
fnName = 'Juvenile_Probation_Log_Cabin_Ranch_Admissions.csv'
        
grpFieldList = 'Log Cabin Ranch Entry Year'
df, titleStuff = makeOutput(datasetName, src_dir , fnName )
titleStuff

In [14]:
grpField = [ df['Log Cabin Ranch Entry Year']]
fieldListString = 'Age at Log Cabin Entry Date, Ethnicity'
fieldList = [ df['Age at Log Cabin Entry Date'],df['Ethnicity']]
crossBy, single_cell_info = makeCrossTabInfo( grpField, grpFieldList, fieldList, fieldListString,  datasetName)
single_cell_info

In [15]:
crossBy

Age at Log Cabin Entry Date            13-17                             \
Ethnicity                   african american asian hispanic other white
Log Cabin Ranch Entry Year
2011                         17               7     3        0     1
2012                         24               3     2        0     1
2013                         11               3     6        0     0
2014                         7                2     3        0     0
2015                         8                2     5        0     0
2016                         2                2     0        1     0

Age at Log Cabin Entry Date              18+
Ethnicity                   african american asian hispanic other
Log Cabin Ranch Entry Year
2011                         1                0     0        0
2012                         1                0     1        0
2013                         0                1     0        1
2014                         2                0     1        0
2015                         4                3     4        0
2016                         1                0     0        0

In [16]:

datasetName = "Juvenile_Probation_Log_Cabin_Ranch_Releases"
src_dir = '/home/ubuntu/workspace/source_data/'
fnName = 'Juvenile_Probation_Log_Cabin_Ranch_Releases.csv'
        
grpFieldList = 'Length of Stay In Log Cabin Ranch Placement'
df, titleStuff = makeOutput(datasetName, src_dir , fnName )
titleStuff

In [17]:
grpField = [ df['Length of Stay In Log Cabin Ranch Placement']]
fieldListString = 'Log Cabin Ranch Entry Year, Age of Youth when released from LCR'
fieldList = [ df['Log Cabin Ranch Entry Year'],df['Age of Youth when released from LCR']]
crossBy, single_cell_info = makeCrossTabInfo( grpField, grpFieldList, fieldList, fieldListString,  datasetName)
single_cell_info

In [18]:
crossBy

Log Cabin Ranch Entry Year                  2009  2010      2011      2012  \
Age of Youth when released from LCR          18+ 13-17 18+ 13-17 18+ 13-17
Length of Stay In Log Cabin Ranch Placement
10                                           0    0     0   0     0   0
15                                           0    0     0   0     0   0
46                                           0    0     0   0     0   0
49                                           0    0     1   0     0   0
57                                           0    0     0   0     0   1
58                                           0    0     0   0     0   0
64                                           0    0     0   1     0   0
86                                           0    0     0   0     0   0
92                                           0    0     0   1     0   0
94                                           0    0     0   0     0   1
95                                           0    0     0   0     0   0
101                                          0    0     0   0     0   1
111                                          0    0     0   0     0   0
117                                          0    0     0   0     0   0
127                                          0    0     0   0     0   1
131                                          0    0     0   0     0   0
132                                          0    0     0   0     0   1
142                                          0    0     0   0     0   0
146                                          0    0     0   0     0   0
147                                          0    0     0   0     0   1
150                                          0    0     0   0     0   1
157                                          0    0     0   0     0   0
169                                          0    0     0   0     0   0
185                                          0    0     0   0     0   0
186                                          0    0     0   0     0   0
201                                          0    0     0   0     0   0
205                                          0    0     0   0     0   0
212                                          0    0     0   0     0   0
213                                          0    0     0   1     0   0
214                                          0    0     0   0     0   0
...                                         ..   ..    ..  ..    ..  ..
313                                          0    0     0   0     0   0
320                                          0    1     0   0     0   0
325                                          0    1     0   0     0   0
326                                          0    0     0   0     0   0
329                                          0    1     0   0     0   0
331                                          0    1     0   0     0   0
332                                          0    0     0   0     0   0
338                                          0    0     0   1     0   0
339                                          0    0     0   0     0   0
340                                          0    0     0   0     0   0
341                                          0    1     0   0     0   0
349                                          0    1     0   0     0   0
350                                          0    0     0   0     0   0
352                                          0    0     0   0     0   0
359                                          0    0     0   0     0   0
360                                          0    0     0   0     0   0
364                                          0    0     0   0     0   0
380                                          0    0     0   0     0   0
389                                          0    0     1   0     0   0
394                                          0    0     0   0     0   0
397                                          0    0     0   0     0   1
410                                          0    0     0   0     0   0
418                                          0    0     0   0     0   1
444                                          0    0     0   1     0   0
456                                          0    0     0   0     0   0
472                                          0    0     0   0     0   0
473                                          0    0     0   0     0   0
478                                          0    0     0   0     0   1
550                                          0    0     1   0     0   0
635                                          1    0     0   0     0   0

Log Cabin Ranch Entry Year                       2013      2014      2015      \
Age of Youth when released from LCR         18+ 13-17 18+ 13-17 18+ 13-17 18+
Length of Stay In Log Cabin Ranch Placement
10                                           0   1     0   0     0   0     0
15                                           0   0     0   0     0   0     1
46                                           0   0     0   0     0   0     1
49                                           0   0     0   0     0   0     0
57                                           0   0     0   0     0   0     0
58                                           0   0     0   0     0   0     0
64                                           0   0     0   0     0   0     0
86                                           0   0     0   0     0   1     0
92                                           0   0     0   0     0   0     0
94                                           0   0     0   0     0   0     0
95                                           0   1     0   0     0   0     0
101                                          0   0     0   0     0   0     0
111                                          0   0     0   0     0   0     1
117                                          0   0     0   1     0   0     0
127                                          0   0     0   0     0   0     0
131                                          0   0     0   0     0   1     0
132                                          0   0     0   0     0   0     0
142                                          0   0     0   0     0   0     1
146                                          1   0     0   0     0   0     0
147                                          0   0     0   0     0   0     0
150                                          0   0     0   0     0   0     0
157                                          0   1     0   0     0   0     0
169                                          0   0     0   1     0   0     0
185                                          0   0     0   0     0   0     1
186                                          0   1     0   0     1   0     0
201                                          0   0     0   0     1   0     0
205                                          0   0     1   0     0   0     0
212                                          0   0     0   0     0   1     0
213                                          0   0     0   0     0   0     0
214                                          0   1     0   0     0   0     0
...                                         ..  ..    ..  ..    ..  ..    ..
313                                          1   0     0   0     0   0     0
320                                          0   0     0   0     0   0     0
325                                          1   0     0   0     0   0     0
326                                          0   1     0   0     0   0     0
329                                          0   0     0   0     0   0     0
331                                          0   0     0   0     0   0     0
332                                          0   0     0   0     0   1     0
338                                          0   0     0   0     0   0     0
339                                          0   0     0   1     0   0     0
340                                          0   0     0   0     0   1     0
341                                          0   0     0   0     0   0     0
349                                          0   0     0   0     0   0     0
350                                          1   0     0   0     0   0     0
352                                          0   0     0   0     0   0     1
359                                          0   1     0   0     0   0     0
360                                          0   0     0   0     0   0     1
364                                          0   0     0   1     0   0     0
380                                          0   1     0   0     0   0     0
389                                          0   0     0   0     0   0     0
394                                          0   0     1   0     0   0     0
397                                          0   0     0   0     0   0     0
410                                          0   1     0   0     0   0     0
418                                          0   0     0   0     0   0     0
444                                          0   0     0   0     0   0     0
456                                          0   0     0   1     0   0     0
472                                          0   1     0   0     0   0     0
473                                          0   1     0   0     0   0     0
478                                          0   0     0   0     0   0     0
550                                          0   0     0   0     0   0     0
635                                          0   0     0   0     0   0     0

Log Cabin Ranch Entry Year                   2016
Age of Youth when released from LCR         13-17
Length of Stay In Log Cabin Ranch Placement
10                                           0
15                                           0
46                                           0
49                                           0
57                                           0
58                                           1
64                                           0
86                                           0
92                                           0
94                                           0
95                                           0
101                                          0
111                                          0
117                                          0
127                                          0
131                                          0
132                                          0
142                                          0
146                                          0
147                                          0
150                                          0
157                                          0
169                                          0
185                                          0
186                                          0
201                                          0
205                                          0
212                                          0
213                                          0
214                                          0
...                                         ..
313                                          0
320                                          0
325                                          0
326                                          0
329                                          0
331                                          0
332                                          0
338                                          0
339                                          0
340                                          0
341                                          0
349                                          0
350                                          0
352                                          0
359                                          0
360                                          0
364                                          0
380                                          0
389                                          0
394                                          0
397                                          0
410                                          0
418                                          0
444                                          0
456                                          0
472                                          0
473                                          0
478                                          0
550                                          0
635                                          0

[106 rows x 14 columns]